{% set name = "metronomes" %}
{% set version = "0.0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/metronomes-{{ version }}.tar.gz
  sha256: 131864ab1f8a45e108af25504b5ed9a7100679afe36d62ae1bf62a72d855bf8c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools ==68.0.0
    - pip
  run:
    - python >=3.7
    - emptylog >=0.0.7
    - cantok >=0.0.23
    - escaping >=0.0.13
    - locklib >=0.0.15
    - typing-extensions

test:
  imports:
    - metronomes
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pomponchik/metronomes
  summary: Endless tick-tock generators.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
