{% set name = "metronomes" %}
{% set version = "0.0.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/metronomes-{{ version }}.tar.gz
  sha256: c0613aaafe8026d48a6d47ed1852f72a687a81404812457112fa3c5ae1f74854

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools ==68.0.0
    - pip
  run:
    - python >={{ python_min }}
    - emptylog >=0.0.7
    - cantok >=0.0.23
    - escaping >=0.0.13
    - locklib >=0.0.15
    - typing-extensions

test:
  imports:
    - metronomes
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pomponchik/metronomes
  summary: Endless tick-tock generators.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
